-- 코드를 입력하세요
SELECT 
    F.FLAVOR
FROM 
    ICECREAM_INFO I
    JOIN
        FIRST_HALF F
    on
        I.FLAVOR = F.FLAVOR
WHERE 
    I.INGREDIENT_TYPE = 'fruit_based'
    AND F.TOTAL_ORDER > 3000
ORDER BY 
    F.TOTAL_ORDER DESC;
# SELECT * FROM FIRST_HALF WHERE TOTAL_ORDER > 3000 ORDER BY TOTAL_ORDER DESC;

# SELECT * FROM ICECREAM_INFO WHERE INGREDIENT_TYPE = 'fruit_based';